name: mini_app_flutter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  camera: ^0.10.5+2
  camera_web: ^0.3.1+4
  flutter:
    sdk: flutter
  flutter_background: ^1.2.0
  flutter_inappwebview: ^5.7.2+3
  flutter_webrtc: ^0.9.36
  permission_handler: ^10.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
